// React Js/task-1/src/components/Header.tsx
import { useEffect } from "react"
import { Link } from "react-router-dom"


const links = [
    {
        'title': 'Home',
        'url': '/',
        'theme': 'bg-warning-subtle'
    },
    {
        'title': 'About',
        'url': '/about',
        'theme': 'bg-success-subtle'
    },
    {
        'title': 'Contact Us',
        'url': '/contact-us',
        'theme': 'bg-primary-subtle'
    }
]

const Header = ({ title, setTitle, theme, setTheme }: any) => {

    useEffect(() => {
        setTitle("Bhavanshu Dalwadi")
    }, [])

    return (
        <nav className={`navbar fixed-top ${theme}`}>
            <div className="container justify-content-start">
                <button className="navbar-toggler box-shadow shadow-sm" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <Link className="navbar-brand ms-3 text-danger-emphasis" to="/" onClick={() => setTheme("bg-warning-subtle")}>{title}</Link>
                <div className="offcanvas offcanvas-start" tabIndex={-1} id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div className="offcanvas-header">
                        <h5 className="offcanvas-title" id="offcanvasNavbarLabel">{title}</h5>
                        <button type="button" className="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div className="offcanvas-body">
                        <ul className="navbar-nav justify-content-end flex-grow-1 pe-3">
                            {links.map((link, index) => 
                                <li className="nav-item" key={index} data-bs-dismiss="offcanvas" aria-label="Close">
                                    <Link className={`nav-link px-2 py-3 text-danger-emphasis rounded-3 mb-2 ${theme}`} aria-current="page" to={link.url} onClick={() => setTheme(link.theme)}>{link.title}</Link>
                                </li>
                            )}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    )
}

export default Header

// E-Commerce Website/ecommarce-angular-frontend/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink],
  template: `
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" routerLink="/">E-Commerce Angular</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" routerLink="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" routerLink="/products">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" routerLink="/contact">Contact</a>
                        </li>
                        @if(!this.authService.authToken) {
                          <li class="nav-item">
                              <a class="nav-link" routerLink="/login">Login</a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" routerLink="/signup">Signup</a>
                          </li>
                        }@else {
                          <li class="nav-item">
                              <a class="nav-link" routerLink="/orders">Orders</a>
                          </li>
                        }
                    </ul>
                    <form class="d-flex" role="search">
                        <a type="button" class="btn btn-primary" routerLink="/cart">
                            <i class="bi bi-cart-fill"></i>
                            <span class='ms-2'>Cart</span>
                        </a>
                        @if(this.authService.authToken) {
                          <button type="button" class="btn btn-danger ms-2" (click)="logoutUser()">
                              <span class='me-2'>Logout</span>
                              <i class="bi bi-box-arrow-right"></i>
                          </button>
                        }
                    </form>
        </div>
      </div>
    </nav>
  `,
  styles: ``
})
export class HeaderComponent {
  constructor(public authService: AuthService, private router: Router) { }

  logoutUser = () => {
    this.authService.logoutUser()
  }
}
