// E-Commerce Website/ecommarce-react-frontend/src/pages/Cart.tsx
import { useEffect, useState } from 'react'
import { useCartContext } from '../contexts/CartProvider'
import { useOrderContext } from '../contexts/OrderProvider'
import { imageURL } from '../API'

const Cart = () => {
  const [totalItems, setTotalItems] = useState<number>(0)
  const [totalAmount, setTotalAmount] = useState<number>(0)
  const [address, setAddress] = useState<string>("")
  const [payment_mode, setPaymentMode] = useState<string>("")
  const { cartItems, getCart, updateCartQty, setCartItems } = useCartContext()
  const { placeOrder } = useOrderContext()

  useEffect(() => {
    getCart()
    return () => { setTotalAmount(0); setTotalItems(0); setCartItems([]); }
  }, [])

  useEffect(() => {
    if(cartItems && cartItems.length > 0) {
      setTotalItems(cartItems.reduce((t: number, c: any) => t + c.quantity , 0))
      setTotalAmount(cartItems.reduce((t: number, c: any) => t + (c.product.price * c.quantity) , 0))
    }
  }, [cartItems])

  const handleQtyUpdate = (pid: string, qty: number) => {
    updateCartQty(pid, qty)
  }

  const handlePlaceOrder = () => {
    if(cartItems && Array.isArray(cartItems) && cartItems.length > 0 && address.trim() != '' && payment_mode.trim() != '') {
      placeOrder(cartItems.map((c: any) => c._id), address.trim(), payment_mode.trim(), `₹ ${totalAmount} Cash`)
    }else {
      alert('Order details are invalid')
    }
  }

  return (
    <div className='row'>
      {cartItems && Array.isArray(cartItems) && cartItems.length === 0?
        <div className="col-md-12">
          <div className="card">
            <div className="card-body text-center">
              <h4>Your Cart is Empty ;)</h4>
            </div>
          </div>
        </div>
      :<div className="col-md-12 p-0">
        <div className="row">
          <div className="col-md-7">
            <div className="d-flex justify-content-between">
              <h5>Basket: ({totalItems})</h5>
              <h5>Total Amount: ₹ {totalAmount}</h5>
            </div>
            {cartItems && cartItems.map((item: any) =>
              <div className="card d-flex flex-row mt-3">
                <img src={`${imageURL}/${item.product.image}`} className="card-img-left" style={{width: 150}} alt="product-image" />
                <div className="card-body">
                  <h5 className="card-title product-name">{item.product.name}</h5>
                  <h4>₹ {item.product.price}</h4>
                  <div className='d-flex justify-content-end'>
                    <button className="btn btn-primary" onClick={() => handleQtyUpdate(item.product._id, item.quantity - 1)}>
                      <i className="bi bi-dash-lg"></i>
                    </button>
                    <span className="card py-1 px-3 fs-5 mx-2">{item.quantity}</span>
                    <button className="btn btn-primary" onClick={() => handleQtyUpdate(item.product._id, item.quantity + 1)}>
                      <i className="bi bi-plus-lg"></i>
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
          <div className="col-md-1"></div>
          <div className="col-md-4">
            <h5 className='mt-5'>Payment and Shiping Details</h5>
            <div className="mb-3">
              <label htmlFor="address" className="form-label">Address</label>
              <textarea className="form-control" id="address" rows={3} onChange={(e) => setAddress(e.target.value)}>{address}</textarea>
            </div>
            <div className="mb-3">
              <label htmlFor="address" className="form-label">Payment Mode</label>
              <select className="form-select" aria-label="Default select example" onChange={(e) => setPaymentMode(e.target.value)} value={payment_mode}>
                <option value="" selected>Select payment mode</option>
                <option value="COD">Cash On Delevery</option>
              </select>
            </div>
            <button className="btn btn-primary w-100" onClick={handlePlaceOrder}>Place Order</button>
          </div>
        </div>
      </div>
      }
    </div>
  )
}

export default Cart

// E-Commerce Website/ecommarce-angular-frontend/src/app/components/cart/cart.component.ts
import { Component, DoCheck, OnInit } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { CartService } from '../../services/cart.service';
import { OrderService } from '../../services/order.service';
import { AuthService } from '../../services/auth.service';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [
    FormsModule,
    ReactiveFormsModule,
    RouterLink
  ],
  templateUrl: './cart.component.html',
  styleUrl: './cart.component.scss'
})
export class CartComponent implements OnInit, DoCheck {
  cartItems: any[] = []

  address: string = ""
  payment_mode: string = ""

  totalItems: number = 0
  totalAmount: number = 0

  constructor(private cartService: CartService, private orderService: OrderService, private authService: AuthService) {}

  ngOnInit() {
    this.getCarts()
  }

  ngDoCheck() {
    if(this.cartItems && this.cartItems.length > 0) {
      this.totalItems = this.cartItems.reduce((t: number, c: any) => t + c.quantity , 0)
      this.totalAmount = this.cartItems.reduce((t: number, c: any) => t + (c.product.price * c.quantity) , 0)
    }
  }

  getCarts = () => {
    this.authService.loading = true
    const promise = this.cartService.getCart()
    if(promise) {
      promise.subscribe({
        next: (response: any) => {
          if(Array.isArray(response)) {
            this.cartItems = response
          }else {
            alert('Failed to get cart')
            console.log(response)
          }
        },
        error: (e: any) => {
          alert("Failed to get cart");
          console.error(e);
        },
        complete: () => {this.authService.loading = false}
      })
    }
  }

  handleQtyUpdate = (product_id: string, qty: number) => {
    if(product_id != '' && qty >= 0) {
      this.authService.loading = true
      const promise = this.cartService.updateCartQty(product_id, qty)
      if(promise) {
        promise.subscribe({
          next: (response: any) => {
            if(response._id) {
              this.getCarts()
            }else {
              console.log('Failed to update cart', response)
              if(response.error) {
                  alert(response.error);
              }
            }
          },
          error: (e: any) => {
            alert('Add to cart failed');
            console.error(e);
          },
          complete: () => {this.authService.loading = false}
        })
      }
    }
  }

  handlePlaceOrder = () => {
    if(this.cartItems && Array.isArray(this.cartItems) && this.cartItems.length > 0 && this.address.trim() != '' && this.payment_mode.trim() != '') {
      let carts = [...this.cartItems]
      this.authService.loading = true
      const promise = this.orderService.placeOrder(carts.map((c: any) => c._id), this.address.trim(), this.payment_mode.trim(), `₹ ${this.totalAmount} Cash`)
      if(promise) {
        promise.subscribe({
          next: (response: any) => {
            if(response._id) {
              alert('Order Placed Successful')
              this.getCarts()
            }else {
              alert('Failed to get cart')
              console.log(response)
            }
          },
          error: (e: any) => {
            alert("Failed to get cart");
            console.error(e);
          },
          complete: () => {this.authService.loading = false}
        })
      }
    }else {
      alert('Order details are invalid')
    }
  }
}

<div class='row'>
    @if(cartItems && cartItems.length === 0) {
        <div class="col-md-12">
          <div class="card">
            <div class="card-body text-center">
              <h4>Your Cart is Empty ...</h4>
            </div>
          </div>
        </div>
    }@else {
        <div class="col-md-12 p-0">
          <div class="row">
            <div class="col-md-7">
              <div class="d-flex justify-content-between">
                <h5>Basket: ({{totalItems}})</h5>
                <h5>Total Amount: ₹ {{totalAmount}}</h5>
              </div>
              @for (item of cartItems; track $index) {
                <div class="card d-flex flex-row mt-3">
                  <img [src]="item.product.image" class="card-img-left" style="width: 150px" alt="product-image" routerLink="/product-details/{{item.product._id}}" />
                  <div class="card-body">
                    <a routerLink="/product-details/{{item.product._id}}" style="color: #000; text-decoration: none;">
                      <h5 class="card-titl product-name">{{item.product.name}}</h5>
                      <h4>₹ {{item.product.price}}</h4>
                    </a>
                    <div class='d-flex justify-content-end'>
                      <button class="btn btn-primary" (click)="handleQtyUpdate(item.product._id, item.quantity - 1)">
                        <i class="bi bi-dash-lg"></i>
                      </button>
                      <span class="card py-1 px-3 fs-5 mx-2">{{item.quantity}}</span>
                      <button class="btn btn-primary" (click)="handleQtyUpdate(item.product._id, item.quantity + 1)">
                        <i class="bi bi-plus-lg"></i>
                      </button>
                    </div>
                  </div>
                </div>
              }
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-4">
              <h5 class="mt-5">Payment and Shiping Details</h5>
              <div class="mb-3">
                <label htmlFor="address" class="form-label">Address</label>
                <textarea class="form-control" id="address" name="address" rows="3" [(ngModel)]="address"></textarea>
              </div> 
              <div class="mb-3">
                <label htmlFor="address" class="form-label">Payment Mode</label>
                <select class="form-select" aria-label="Default select example" name="payment_mode" [(ngModel)]="payment_mode">
                  <option value="" selected>Select payment mode</option>
                  <option value="COD">Cash On Delevery</option>
                </select>
              </div>
              <button class="btn btn-primary w-100" (click)="handlePlaceOrder()">Place Order</button>
            </div>
          </div>
        </div>
    }
</div>
