// E-Commerce Website/ecommarce-react-frontend/src/pages/ProductDetails.tsx
import { useEffect } from "react"
import { Link, useParams } from "react-router-dom"
import { useProductContext } from "../contexts/ProductProvider"
import { useCartContext } from "../contexts/CartProvider"
import { imageURL } from "../API"

const ProductDetails = () => {
    const { id } = useParams()
    const { product, getProductDetails, setProduct } = useProductContext()
    const { getCart, cartItems, addToCart, updateCartQty } = useCartContext()

    useEffect(() => {
        if (product && cartItems) {
            let carts = [...cartItems]
            setProduct({ ...product, qty: carts.find((c: any) => c.product._id === product._id) != undefined ? carts.find((c: any) => c.product._id === product._id).quantity : 0 })
        }
    }, [cartItems])

    const handleAddToCart = (pid: string) => {
        addToCart(pid)
    }

    const handleQtyUpdate = (pid: string, qty: number) => {
        updateCartQty(pid, qty)
    }

    useEffect(() => {
        if (id && id.trim() != '') {
            getProductDetails(id);
        }
        getCart()

        return () => setProduct(null)
    }, [])

    return (
        <div className="row">
            <div className="col-md-3"></div>
            <div className="col-md-6">
                {product ?
                    <div className="card text-center">
                        <h3 className="card-title m-3">{product.name}</h3>
                        <img src={`${imageURL}/${product.image}`} className="card-img-top" alt="product-image" />
                        <div className="card-body">
                            <h4>Price: ₹ {product.price}</h4>
                                {product.qty && product.qty != 0
                                    ?<>
                                        <div className='d-flex justify-content-center'>
                                            <button className="btn btn-primary" onClick={() => handleQtyUpdate(product._id, product.qty - 1)}>
                                                <i className="bi bi-dash-lg"></i>
                                            </button>
                                            <span className="card py-1 px-3 fs-5 mx-2">{product.qty}</span>
                                            <button className="btn btn-primary" onClick={() => handleQtyUpdate(product._id, product.qty + 1)}>
                                                <i className="bi bi-plus-lg"></i>
                                            </button>
                                        </div>
                                        <Link className="btn btn-primary w-50 mt-3" to='/cart'>Go To Cart</Link>
                                    </>
                                    :<button className="btn btn-primary w-50" onClick={() => handleAddToCart(product._id)}>Add To Cart</button>
                                }
                        </div>
                    </div>
                :<></>}
            </div>
            <div className="col-md-3"></div>
        </div>
    )
}

export default ProductDetails

// E-Commerce Website/ecommarce-angular-frontend/src/app/components/product-details/product-details.component.ts
import { Component, DoCheck, OnInit } from '@angular/core';
import { ProductService } from '../../services/product.service';
import { CartService } from '../../services/cart.service';
import { AuthService } from '../../services/auth.service';
import { ActivatedRoute, RouterLink } from '@angular/router';

@Component({
  selector: 'app-product-details',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './product-details.component.html',
  styleUrl: './product-details.component.scss'
})
export class ProductDetailsComponent implements OnInit, DoCheck {
  product_id: string = ""
  product: any = null
  cart: any[] = []

  constructor(private route: ActivatedRoute, private productService: ProductService, private cartService: CartService, private authService: AuthService) {}

  ngOnInit() {
    this.route.params.subscribe(params => {
      this.product_id = params['id'];
      this.getProduct()
    });
    this.getCarts()
  }

  ngDoCheck() {
    if(this.product && this.cart) {
      let carts = [...this.cart]
      this.product.qty = carts.find((c: any) => c.product._id === this.product._id) != undefined?carts.find((c: any) => c.product._id === this.product._id).quantity:0;
    }
  }

  getProduct = () => {
    this.authService.loading = true
    this.productService.getProductDetails(this.product_id).subscribe({
      next: (response: any) => {
        if(response._id) {
          this.product = response
        }else {
          alert('Failed to get product')
          console.log(response)
        }
      },
      error: (e) => {
        alert("Failed to get product");
        console.error(e);
      },
      complete: () => {this.authService.loading = false}
    })
  }

  getCarts = () => {
    const promise = this.cartService.getCart()
    if(promise) {
      promise.subscribe({
        next: (response: any) => {
          if(Array.isArray(response)) {
            this.cart = response
          }else {
            alert('Failed to get cart')
            console.log(response)
          }
        },
        error: (e) => {
          alert("Failed to get cart");
          console.error(e);
        },
        complete: () => {this.authService.loading = false}
      })
    }
  }

  handleAddToCart = () => {
    this.authService.loading = true
    if(this.product_id != '') {
      const promise = this.cartService.addToCart(this.product_id)
      if(promise) {
        promise.subscribe({
          next: (response: any) => {
            if(response._id) {
              alert('Item added to cart');
              this.getCarts()
            }
          },
          error: (e) => {
            alert('Add to cart failed');
            console.error(e);
          },
          complete: () => {this.authService.loading = false}
        })
      }
    }
  }

  handleQtyUpdate = (qty: number) => {
    this.authService.loading = true
    if(this.product_id != '' && qty >= 0) {
      const promise = this.cartService.updateCartQty(this.product_id, qty)
      if(promise) {
        promise.subscribe({
          next: (response: any) => {
            if(response._id) {
              this.getCarts()
            }else {
              console.log('Failed to update cart', response)
              if(response.error) {
                  alert(response.error);
              }
            }
          },
          error: (e) => {
            alert('Add to cart failed');
            console.error(e);
          },
          complete: () => {this.authService.loading = false}
        })
      }
    }
  }
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        @if (product) {
            <div class="card text-center">
                <h3 class="card-title m-3">{{product.name}}</h3>
                <img [src]="product.image" class="card-img-top" alt="product-image" />
                <div class="card-body">
                    <h4>Price: ₹ {{product.price}}</h4>
                        @if(product.qty && product.qty != 0) {
                            <div class='d-flex justify-content-center'>
                                <button class="btn btn-primary" (click)="handleQtyUpdate(product.qty - 1)">
                                    <i class="bi bi-dash-lg"></i>
                                </button>
                                <span class="card py-1 px-3 fs-5 mx-2">{{product.qty}}</span>
                                <button class="btn btn-primary" (click)="handleQtyUpdate(product.qty + 1)">
                                    <i class="bi bi-plus-lg"></i>
                                </button>
                            </div>
                            <a class="btn btn-primary w-50 mt-3" routerLink='/cart'>Go To Cart</a>
                        }@else {
                            <button class="btn btn-primary w-50" (click)="handleAddToCart()">Add To Cart</button>
                        }
                </div>
            </div>
        }
    </div>
    <div class="col-md-3"></div>
</div>
