// E-Commerce Website/ecommarce-angular-frontend/src/app/components/products/products.component.ts
import { Component, DoCheck, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ProductService } from '../../services/product.service';
import { CartService } from '../../services/cart.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './products.component.html',
  styleUrl: './products.component.scss'
})
export class ProductsComponent implements OnInit, DoCheck {
  products: any[] = []
  cart: any[] = []

  constructor(private productService: ProductService, private cartService: CartService, private authService: AuthService) {}

  ngOnInit() {
    this.getProductList()
    this.getCarts()
  }

  ngDoCheck() {
    if(this.products && this.cart) {
      let carts = [...this.cart]
      this.products.filter((p: any) => { p.qty = carts.find((c: any) => c.product._id === p._id) != undefined?carts.find((c: any) => c.product._id === p._id).quantity:0; return true; })
    }
  }

  getProductList = () => {
    this.authService.loading = true
    this.productService.getProducts().subscribe({
      next: (response: any) => {
        if(Array.isArray(response)) {
          this.products = response
        }else {
          alert('Failed to get products')
          console.log(response)
        }
      },
      error: (e) => {
        alert("Failed to get products");
        console.error(e);
      },
      complete: () => {this.authService.loading = false}
    })
  }

  getCarts = () => {
    const promise = this.cartService.getCart()
    if(promise) {
      promise.subscribe({
        next: (response: any) => {
          if(Array.isArray(response)) {
            this.cart = response
          }else {
            alert('Failed to get cart')
            console.log(response)
          }
        },
        error: (e) => {
          alert("Failed to get cart");
          console.error(e);
        },
        complete: () => {this.authService.loading = false}
      })
    }
  }

  handleAddToCart = (product_id: string) => {
    this.authService.loading = true
    if(product_id != '') {
      const promise = this.cartService.addToCart(product_id)
      if(promise) {
        promise.subscribe({
          next: (response: any) => {
            if(response._id) {
              alert('Item added to cart');
              this.getCarts()
            }
          },
          error: (e) => {
            alert('Add to cart failed');
            console.error(e);
          },
          complete: () => {this.authService.loading = false}
        })
      }
    }
  }

  handleQtyUpdate = (product_id: string, qty: number) => {
    this.authService.loading = true
    if(product_id != '' && qty >= 0) {
      const promise = this.cartService.updateCartQty(product_id, qty)
      if(promise) {
        promise.subscribe({
          next: (response: any) => {
            if(response._id) {
              this.getCarts()
            }else {
              console.log('Failed to update cart', response)
              if(response.error) {
                  alert(response.error);
              }
            }
          },
          error: (e) => {
            alert('Add to cart failed');
            console.error(e);
          },
          complete: () => {this.authService.loading = false}
        })
      }
    }
  }
}

<div>
    <h3>Product List</h3>
    <div class="row mt-3">
        @for (p of products; track $index) {
            <div class="col-md-3" key={p._id}>
                <div class="card mt-3">
                    <a [routerLink]="['/product-details', p._id]">
                        <img [src]="p.image" class="card-img-top" style="height: 290px" alt="product-image" />
                    </a>
                        <div class="card-body">
                            <a [routerLink]="['/product-details', p._id]" style="text-decoration: none; color: #000">
                                <h5 class="card-title product-name">{{ p.name }}</h5>
                                <h4>₹ {{ p.price }}</h4>
                            </a>
                            @if (p.qty === 0) {
                                <button class="btn btn-primary w-100" (click)='handleAddToCart(p._id)'>Add To Cart</button>
                            } @else {
                                <div class='d-flex justify-content-end'>
                                    <button class="btn btn-primary" (click)='handleQtyUpdate(p._id, p.qty - 1)'>
                                        <i class="bi bi-dash-lg"></i>
                                    </button>
                                    <span class="card py-1 px-3 fs-5 mx-2">{{ p.qty }}</span>
                                    <button class="btn btn-primary" (click)='handleQtyUpdate(p._id, p.qty + 1)'>
                                        <i class="bi bi-plus-lg"></i>
                                    </button>
                                </div>
                            }
                        </div>
                </div>
            </div>
        }
    </div>
</div>

// E-Commerce Website/ecommarce-react-frontend/src/pages/Products.tsx
import { useEffect, useState } from 'react'
import { useProductContext } from '../contexts/ProductProvider'
import { useCartContext } from '../contexts/CartProvider'
import { Link } from 'react-router-dom'
import { imageURL } from '../API'

const Products = ({ as }: any) => {
    const [productList, setProductList] = useState<any>([])
    const { getProducts, products } = useProductContext()
    const { getCart, cartItems, addToCart, updateCartQty } = useCartContext()

    useEffect(() => {
        if(products && cartItems && products.length > 0) {
            console.log('called')
            let items = [...products]
            let carts = [...cartItems]
            setProductList(items.filter((p: any) => { p.qty = carts.find((c: any) => c.product._id === p._id) != undefined?carts.find((c: any) => c.product._id === p._id).quantity:0; return true; }))
        }
    }, [cartItems, products])

    useEffect(() => {
        getProducts()
        getCart()
    }, [])

    const handleAddToCart = (pid: string) => {
        addToCart(pid)
    }

    const handleQtyUpdate = (pid: string, qty: number) => {
        updateCartQty(pid, qty)
    }

    return (
        <div key={productList}>
            <h3>{as}</h3>
            <div className="row mt-3">
                {productList && productList.map((p: any) =>
                    <div className="col-md-3" key={p._id}>
                        <div className="card mt-3">
                            <Link to={`/product-details/${p._id}`}>
                                <img src={`${imageURL}/${p.image}`} className="card-img-top" style={{height: 290}} alt="product-image" />
                            </Link>
                                <div className="card-body">
                                    <Link to={`/product-details/${p._id}`} style={{textDecoration: 'none', color: '#000'}}>
                                        <h5 className="card-title product-name">{p.name}</h5>
                                        <h4>₹ {p.price}</h4>
                                    </Link>
                                    { p.qty === 0
                                        ? <button className="btn btn-primary w-100" onClick={() => handleAddToCart(p._id)}>Add To Cart</button>
                                        : <div className='d-flex justify-content-end'>
                                            <button className="btn btn-primary" onClick={() => handleQtyUpdate(p._id, p.qty - 1)}>
                                                <i className="bi bi-dash-lg"></i>
                                            </button>
                                            <span className="card py-1 px-3 fs-5 mx-2">{p.qty}</span>
                                            <button className="btn btn-primary" onClick={() => handleQtyUpdate(p._id, p.qty + 1)}>
                                                <i className="bi bi-plus-lg"></i>
                                            </button>
                                        </div>
                                    }
                                </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    )
}

export default Products
